#┌──────────────────────────────────────────────────────────────────────────────────┐
#│                           ______   __       ____    ______                       │
#│                   /'\_/`\/\__  _\ /\ \     /\  _`\ /\  _  \                      │██
#│                  /\      \/_/\ \/ \ \ \    \ \ \L\ \ \ \L\ \                     │██
#│                  \ \ \__\ \ \ \ \  \ \ \  __\ \ ,__/\ \  __ \                    │██
#│                   \ \ \_/\ \ \_\ \__\ \ \L\ \\ \ \/  \ \ \/\ \                   │██
#│                    \ \_\\ \_\/\_____\\ \____/ \ \_\   \ \_\ \_\                  │██
#│                     \/_/ \/_/\/_____/ \/___/   \/_/    \/_/\/_/                  │██
#│                                                                                  │██
#│                                                                                  │██
#│                 ___                            __           ___                  │██
#│                /\_ \                          /\ \__       /\_ \                 │██
#│      _ __   ___\//\ \      __      ____    ___\ \ ,_\    __\//\ \     ___        │██
#│     /\`'__\/ __`\\ \ \   /'__`\   /',__\  / __`\ \ \/  /'__`\\ \ \   / __`\      │██
#│     \ \ \//\ \L\ \\_\ \_/\ \L\.\_/\__, `\/\ \L\ \ \ \_/\  __/ \_\ \_/\ \L\ \     │██
#│      \ \_\\ \____//\____\ \__/.\_\/\____/\ \____/\ \__\ \____\/\____\ \____/     │██
#│       \/_/ \/___/ \/____/\/__/\/_/\/___/  \/___/  \/__/\/____/\/____/\/___/      │██
#│                                                                                  │██
#└──────────────────────────────────────────────────────────────────────────────────┘██
#████████████████████████████████████████████████████████████████████████████████████
#████████████████████████████████████████████████████████████████████████████████████
---
coverage:
  status:
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 10%  # the leniency in hitting the target