import { SlotType } from "../common/enums.js";
import Item from "./Item.js";

/**
 * @class Slot
 * @description Represents a slot in the board, where cards can be played
 * @property {string} id - Slot id
 * @property {SlotType} type - Slot type, either "milpa" or "edge". The Slot type can activate or deactivate some effects in items and cards, or even prevent the use of some cards.
 * @property {Item[]} items - Items contained in the slot
 * @property position - Slot position in the board. A number between 1 and 16
 * @since 1.0.0
 */

class Slot {
  position: number;

  type: SlotType;

  // Each slot can contain a list of items, normally generated by cards
  items: Item[] = [];

  constructor(position: number, type: SlotType, items?: Item[]) {
    this.position = position;
    this.type = type;
    this.items = items || [];
  }
}

export default Slot;
