import {SlotType} from "../common/enums.js";
import Item from "./Item.js";

class Slot {
    // Number from 1 to 16 to represent the position of the slot
    position: number;

    // Type of the slot, either milpa or edge (at the moment).
    // The Slot type can activate or deactivate some effects in items and cards,
    // or even prevent the use of some cards.
    type: SlotType;

    // Each slot can contain a list of items, normally generated by cards
    items: Item[] = [];

    constructor(
        position: number,
        type: SlotType,
        items?: Item[]
    ) {
        this.position = position;
        this.type = type;
        this.items = items || [];
    }

}

export default Slot;